import { Inter } from "next/font/google";
import "./globals.css";
import bg from "/public/bgdavinci.png"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Davinci",
  description: "Generated by create Ramazan",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body style={{ backgroundImage: `url(${bg.src})`, backgroundSize: 'cover' }} className={inter.className}>{children}
      
   
      </body>
     
    </html>
  );
}
